### ISSUE TITLE
Configure button/icon

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/field_wrappers#4] opened 2019-06-20 13:52 UTC
Split out from https://github.com/backdrop-contrib/field_wrappers/issues/1

> There's one new issue (or I didn't notice it last time): The image of the Configure button is not displayed. Looking at the src of the field_image_formatter_settings_edit input element with the browser inspector I see:

> http://example.com/misc/configure.png

> Should be:

> http://example.com/core/misc/configure.png

**Comment by laryn** [comment] 2019-06-24 16:25
@olafgrabienski I took a quick look at this but don't see any reference to the configure icon in this module. Is this due to core or a separate module?

**Comment by olafgrabienski** [comment] 2019-06-26 08:25
@laryn Thanks for taking a look at it! I've checked my current test site, and now I also don't find any reference to an image for the *Configure* button. Unfortunately, I don't remember exactly if I used this particular test site or another one. It might also be the case that I disabled some modules in the meantime. Anyway, I can't reproduce the issue anymore, so I think we can close it.

**Closed as completed by olafgrabienski** 2019-06-26 08:25 UTC
